name: Generate Snake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # runs at every 00:00 UTC daily

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: Platane/snk@v3
        with:
          github_user_name: dloorah
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push the generated snake
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
